name: Copilot Chat Tests
on:
  workflow_dispatch:
  push:
    branches: [ "main", "feature*" ]
    paths: 
      - 'samples/apps/copilot-chat-app/**'
  pull_request:
    branches: [ "main", "feature*" ]
    paths: 
      - 'samples/apps/copilot-chat-app/**'

jobs:
  test:
    defaults:
      run:
        working-directory: samples/apps/copilot-chat-app/webapp
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      env:
        REACT_APP_BACKEND_URI: https://localhost:40443/
        REACT_APP_AAD_CLIENT_ID: ${{ secrets.COPILOT_CHAT_REACT_APP_AAD_CLIENT_ID }}
        REACT_APP_AAD_AUTHORITY: https://login.microsoftonline.com/common
        TEST_USER_ACCOUNT: ${{ secrets.COPILOT_CHAT_TEST_USER_ACCOUNT }}
        TEST_USER_PASSWORD: ${{ secrets.COPILOT_CHAT_TEST_USER_PASSWORD }}
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30